### ISSUE TITLE
Supporting Libraries are not Public

### ISSUE THREAD

**Issue by Keegan-lee** [PBSA/BookiePro#1]
https://github.com/PBSA/BookiePro/blob/35553c7d939f13d8aa5b421fe294feec8be5850e/package.json#L60
https://github.com/PBSA/BookiePro/blob/35553c7d939f13d8aa5b421fe294feec8be5850e/package.json#L61

Synchronize these libraries with the publicly available libraries.

**Comment by mseaward** [comment]
Resolved
